
{% set cf_buildnumber = "0" %}
{% set py_tag = "py" + PY_VER|replace('.','') %}
{% set intel_ch = "https://software.repos.intel.com/python/conda" %}

# gonna have to change these every time we repack new SVS packages
# scalable-vs repack info
{% set intel_buildnumber = "1" %}
{% set build_string = "g334e1ca" %}
{% set version = "0.1.0" %}
{% set sha256_map = {
  "py310": "57e5b4e93485ec5c6abfa63c9b868c4ce0d0447f1eaa5111604f6160bafb479d",
  "py311": "3945cc2f7ee857aa013fe6d1f4c034da8aee919a0f1212c62bbec46710e5b806",
  "py312": "c7397886c3efd92d6385edde4b275ee4118dfad215f82f81353ba7929e824432",
  "py313": "b4df256ae4af7b1d761ec9987a1ef3685f225d533630f818ae52854c39de25d3",
  "py314": "a693fc21116d507fa625a13d391cfa7df83b1b64a931ba822f4fc8cfcdb090ac"
} %}
# libsvs repack info
{% set libsvs_build_string = build_string %}
{% set libsvs_sha256 = "d3e11aa249a9498a3670cd86a9752172465465a6e5843c3eac3abdf43a44165e" %}
# libsvs-runtime repack info
{% set libsvs_runtime_build_string = "g613ed17" %}
{% set libsvs_runtime_sha256 = "983da705dbb45f8f6b93ae38982f74b1654090c2e4055bca44d22c020f60c1a9" %}

# builds off above variables
{% set url_string =  build_string + py_tag + "_" + intel_buildnumber %}
{% set full_build_string = url_string + "_" + cf_buildnumber %}
{% set libsvs_url_string =  libsvs_build_string + "_" + intel_buildnumber %}
{% set libsvs_full_build_string = libsvs_url_string + "_" + cf_buildnumber %}
{% set libsvs_runtime_url_string =  libsvs_runtime_build_string + "_" + intel_buildnumber %}
{% set libsvs_runtime_full_build_string = libsvs_runtime_url_string + "_" + cf_buildnumber %}

package:
  name: scalable-vs-packs
  version: {{ version }}

source:
  - url: {{ intel_ch }}/{{ target_platform }}/scalable-vs-{{ version }}-{{ url_string }}.conda
    folder: scalable-vs
    sha256: {{ sha256_map[py_tag] }}
    no_hoist: true
  - url: {{ intel_ch }}/{{ target_platform }}/libsvs-{{ version }}-{{ libsvs_url_string }}.conda
    folder: libsvs
    sha256: {{ libsvs_sha256 }}
    no_hoist: true
  - url: {{ intel_ch }}/{{ target_platform }}/libsvs-runtime-{{ version }}-{{ libsvs_runtime_url_string }}.conda
    folder: libsvs-runtime
    sha256: {{ libsvs_runtime_sha256 }}
    no_hoist: true

build:
  number: {{ cf_buildnumber }}
  binary_relocation: false
  detect_binary_files_with_prefix: false
  skip: True  # [not (linux64) or py>313]
  missing_dso_whitelist:
    - /lib64/ld-linux-x86-64.so.2
    - /lib64/libpthread.so.0
    - /lib64/libm.so.6
    - /lib64/libdl.so.2
    - /lib64/libc.so.6

outputs:
  - name: scalable-vs
    version: {{ version }}
    script: repack.sh
    number: {{ cf_buildnumber }}
    build:
      string: {{ full_build_string }}
    requirements:
      host:
        - python
        - conda-package-handling
      run:
        - python
        - numpy
        - toml
        - libstdcxx
        - libgcc
        - libgfortran5
        - libgomp

    about:
      home: https://intel.github.io/ScalableVectorSearch/index.html
      license: Intel Simplified Software License (Version October 2022)
      license_file:
        - scalable-vs/info/licenses/distributions/LICENSE
        - scalable-vs/info/licenses/ScalableVectorSearch/THIRD-PARTY-PROGRAMS
      summary: Scalable Vector Search
      description: |
        <strong>LEGAL NOTICE: Use of this software package is subject to the
        software license agreement (as set forth above, in the license section of
        the installed Conda package and/or the README file) and all notices,
        disclaimers or license terms for third party or open source software
        included in or with the software.</strong>
        <br/><br/>
        EULA: <a href="https://www.intel.com/content/www/us/en/content-details/749362/intel-simplified-software-license-version-october-2022.html" target="_blank">Intel Simplified Software License (Version October 2022)</a>
        <br/><br/>
      dev_url: https://github.com/intel/ScalableVectorSearch
      doc_url: https://intel.github.io/ScalableVectorSearch/index.html
    
    test:
      requires:
        - python
        - numpy
        - toml
      commands:
        - python -c "import sys,os; print('Python:',sys.version); import svs; print('svs ok', svs.library_version())"

  - name: libsvs
    version: {{ version }}
    script: repack_libsvs.sh
    number: {{ cf_buildnumber }}
    build:
      string: {{ libsvs_full_build_string }}
      skip: True  # [not linux64]
    requirements:
      host:
        - conda-package-handling
      run:
        - python >=3.10
        - libstdcxx
        - libgcc
    about:
      home: https://intel.github.io/ScalableVectorSearch/index.html
      license: Intel Simplified Software License (Version October 2022)
      license_file:
        - libsvs/info/licenses/distributions/LICENSE
        - libsvs/info/licenses/ScalableVectorSearch/THIRD-PARTY-PROGRAMS
      summary: Scalable Vector Search library
      dev_url: https://github.com/intel/ScalableVectorSearch
      doc_url: https://intel.github.io/ScalableVectorSearch/index.html
    test:
      commands:
        - test -f $PREFIX/lib/libsvs_shared_library.so
        - test -f $PREFIX/lib/libsvs_static_library.a
        - test -f $PREFIX/include/svs/leanvec/leanvec.h

  - name: libsvs-runtime
    version: {{ version }}
    script: repack_libsvs_runtime.sh
    number: {{ cf_buildnumber }}
    build:
      string: {{ libsvs_runtime_full_build_string }}
      skip: True  # [not linux64]
    requirements:
      host:
        - conda-package-handling
      run:
        - python >=3.10
        - libstdcxx
        - libgcc
    about:
      home: https://intel.github.io/ScalableVectorSearch/index.html
      license: Intel Simplified Software License (Version October 2022)
      license_file:
        - libsvs-runtime/info/licenses/distributions/LICENSE
        - libsvs-runtime/info/licenses/ScalableVectorSearch/THIRD-PARTY-PROGRAMS
      summary: Scalable Vector Search runtime library
      dev_url: https://github.com/intel/ScalableVectorSearch
      doc_url: https://intel.github.io/ScalableVectorSearch/index.html
    test:
      commands:
        - test -f $PREFIX/lib/libsvs_runtime.so
        - test -f $PREFIX/include/svs/runtime/api_defs.h

# pleases the linter
about:
  home: https://github.com/conda-forge/scalable-vs-feedstock
  license: LicenseRef-IntelSimplifiedSoftwareOct2022
  summary: 'Repackaged Intel Scalable Vector Search'

extra:
  feedstock-name: scalable-vs-packs
  recipe-maintainers:
    - jharlow-intel
    - napetrov
    - mihaic
    - ethanglaser
